/**
 * connpass API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: (see docs)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Event

/**
 * 
 * @param resultsReturned 含まれる検索結果の件数
 * @param resultsAvailable 検索結果の総件数
 * @param resultsStart 検索の開始位置
 * @param events 検索結果のイベントリスト
 */
data class GetEventResponse (

    /* 含まれる検索結果の件数 */
    val resultsReturned: kotlin.Int? = null,
    /* 検索結果の総件数 */
    val resultsAvailable: kotlin.Int? = null,
    /* 検索の開始位置 */
    val resultsStart: kotlin.Int? = null,
    /* 検索結果のイベントリスト */
    val events: kotlin.Array<Event>? = null
) {
}