/**
 * connpass API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: (see docs)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id グループID
 * @param title グループタイトル
 * @param url グループのconnpass.com 上のURL
 */
data class Series (

    /* グループID */
    val id: kotlin.Int? = null,
    /* グループタイトル */
    val title: kotlin.String? = null,
    /* グループのconnpass.com 上のURL */
    val url: kotlin.String? = null
) {
}